# Generated by Django 4.2.18 on 2025-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('school', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HeroDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_address', models.CharField(max_length=1024)),
                ('resume_link', models.CharField(max_length=1024)),
                ('typewriter_text', models.JSONField(default=list)),
                ('hero_bio', models.TextField()),
                ('about_me', models.TextField()),
                ('github_link', models.CharField(max_length=1024)),
                ('linkedin_link', models.CharField(max_length=1024)),
                ('instagram_link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('orientation', models.CharField(default='landscape', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
    ]
