# Generated by Django 4.2.18 on 2025-01-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='isLeft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='photo_address',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
