# Generated by Django 4.2.18 on 2025-01-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animation',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
